### PR TITLE
Improving web UI

### PR DESCRIPTION
**Pull request by theo-basty**
I spent some time to improve your web UI for the shuffler :
* adding bootstrap to beautify and simplify styling,
* moving custom style to an external file,
* moving index file to PHP to generate some forms part,
* using selects instead of inputs with datalibs for cards choice to avoid bad inputs and inconveniences

Because I don't have the device itself, I just checked the generation in data.txt but it seemed correct.
If you need help with that, ask me and i will see how i can help :)

### CODE REVIEW

**Comment by TheDigitalGuru** [comment]
I was thinking about building this machine with 12 bays and using it to set
decks.

Is there anyway you could help with that programming and include an option
to do so on the web interface you've just updated?

**Comment by theo-basty** [comment]
I didn't look into the python part yet so I'm not sure if I can hep you with the sorting process. However, I can help you with the UI part ! I would just need some details on what i need to build. I will have to rarrange the different forms.

If i undertand correctly, what you want is an interface which will allow :
* to choose a number of players
* to define specific cards for each players

For the features, would you want to be able to define random cards in those hands ? Are there other options that should be added ?

**Comment by TheDigitalGuru** [comment]
I was hoping to sort the cards as they come brand new. By suit and numerical  denomination.  I figured the machine would have to separate the cards by suit first, in the top 4 bins, then numsrically in the latter 13 bins, of which,  I'd have to add a few to the original concept. Because this project would have to be expanded with more bins, I thought this other project (see link below) I discovered in my hunt might be easier to re-sort my decks if I can track down the tutorial for it again. https://www.youtube.com/watch?v=QtOYimYpdUM I’m mid dev another project atm, but setting decks is what I’ll be looking to do if I pick either one of these projects.  On Sat, Oct 23, 2021, 10:08 AM Théo Basty ***@***.***> wrote:I didn't look into the python part yet so I'm not sure if I can hep you with the sorting process. However, I can help you with the UI part ! I would just need some details on what i need to build. I will have to rarrange the different forms.If i undertand correctly, what you want is an interface which will allow :to choose a number of playersto define specific cards for each playersFor the features, would you want to be able to define random cards in those hands ? Are there other options that should be added ?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DDeGonge** [comment]
Apologies for the delay. Merging this into a dedicated branch since I also have no way to verify the changes do not impact the functionality (the device was disassembled in anticipation of V2 but I have had other projects jump the queue!)

**Pull request merged**
